name: ToDo App Workflow

# このワークフローは、リポジトリにプッシュされたときにトリガーされます
on: [push]

jobs:
  build:
    # Ubuntu 最新バージョンのランナーを使用
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - uses: actions/checkout@v2
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Docker Compose を使用してイメージをビルドし、ACR にプッシュ
    - name: Build and Push Docker Image
      env:
        COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
        COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}
      run: |
        docker-compose -f docker-compose.prod.yml build \
          --build-arg COSMOS_DB_ENDPOINT=${COSMOS_DB_ENDPOINT} \
          --build-arg COSMOS_DB_KEY=${COSMOS_DB_KEY}
        docker tag todo-app:latest acrudemylearn-b6gjgtfqcpedffhj.azurecr.io/todo-app:${{ github.sha }}
        docker push acrudemylearn-b6gjgtfqcpedffhj.azurecr.io/todo-app:${{ github.sha }}
  
    - name: deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: acrudemylearn-b6gjgtfqcpedffhj
        containerAppName: todo-app
        resourceGroup: udemy-container-cicd
        imageToDeploy: acrudemylearn-b6gjgtfqcpedffhj/todo-app:${{ github.sha }}