name: ToDo App Workflow

# このワークフローは、リポジトリにプッシュされたときにトリガーされます
on: [push]

jobs:
  build:
    # Ubuntu 最新バージョンのランナーを使用
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - uses: actions/checkout@v2
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/todo-app
        acrName: acrudemylearn
        containerAppName: todoapp
        resourceGroup: udemy-container-cicd
        environmentVariables: |
          COSMOS_DB_ENDPOINT=${{ secrets.COSMOS_DB_ENDPOINT }}
          COSMOS_DB_KEY=${{ secrets.COSMOS_DB_KEY }}